# Generated by Django 3.2 on 2024-01-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_images/'),
        ),
    ]
